services:
    ai_service:
        build: ./ai-service
        image: civic-ai-service:latest
        container_name: ai-service
        working_dir: /app
        volumes:
            - ./ai-service:/app
        ports:
            - "${AI_PORT}:8000"
        env_file:
            - .env
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
    user_service:
        build: ./user-service
        image: civic-user-service:latest
        container_name: user-service
        working_dir: /app
        volumes:
            - ./user-service:/app
        ports:
            - "${USER_PORT}:8000"
        env_file:
            - .env
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    complaint_service:
        build: ./complaint-service
        image: civic-complaint-service:latest
        container_name: complaint-service
        working_dir: /app
        volumes:
            - ./complaint-service:/app
        ports:
            - "${COMPLAINT_PORT}:8000"
        env_file:
            - .env
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    frontend_service:
        build: ./frontend-service
        image: civic-frontend-service:latest
        container_name: frontend-service
        working_dir: /app
        volumes:
            - ./frontend-service:/app
        ports:
            - "${FRONTEND_PORT}:8000"
        env_file:
            - .env
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
    redis:
        image: redis:trixie
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
        command: redis-server --appendonly yes

    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: civil_intelligent_system_user
            POSTGRES_PASSWORD: cis_password
            POSTGRES_DB: civic_intelligent_system
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./init/data.dump:/docker-entrypoint-initdb.d/data.dump

volumes:
    postgres-data:
    redis-data:
